### ISSUE TITLE
tanya

### ISSUE THREAD

**Issue by arifikhsan** [cahkla10/Appium-Swiping-using-UiScrollable#1]
ada contoh appium yang mengetes memakai 2 emulator android bersamaan?

**Comment by cahkla10** [comment]
@arifikhsan bisa dicoba ke sini ya mas https://github.com/cahkla10/AppiumJavaParalelTest .. tapi mungkin perlu ada penyesuaian karena sepertinya ada beberapa lib yang sudah deprecated

**Comment by arifikhsan** [comment]
terima kasih contohnya mas. selanjutnya apakah appium bisa mengetes pada 2 emulator untuk 2 aplikasi yang berbeda?

**Comment by cahkla10** [comment]
@arifikhsan dari saya belum pernah coba mas, tapi saya pikir bisa ya. Mungkin nanti bikin parameter di xml nya untuk app package dan app activitynya dideclare di situ.

**Comment by arifikhsan** [comment]
baik mas, saya akan mencobanya. terima kasih banyak atas contoh kode nya 👌
